package docs

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// generatedHeader marks every emitted page. It names the regeneration owner so the next
// contributor to open one of these files learns where the content actually comes from: the
// opencharly/docs repo's deploy workflow regenerates this tree against its pinned charly
// checkout (a docs PR bumps that pin and carries the regenerated pages).
const generatedHeader = "<!-- DO-NOT-EDIT — generated by `charly docs generate`; the opencharly/docs repo's deploy workflow regenerates this tree against its pinned charly checkout. -->"

// page is one markdown file to write.
type page struct {
	// Path is relative to the docs content root, e.g. "reference/candy/ripgrep.md".
	Path        string
	Title       string
	Description string
	Body        string
}

// write renders the page with Starlight frontmatter and the generated-file header.
func (p page) write(outRoot string) error {
	dest := filepath.Join(outRoot, filepath.FromSlash(p.Path))
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return fmt.Errorf("mkdir for %s: %w", p.Path, err)
	}
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "title: %s\n", yamlString(p.Title))
	if d := firstLine(p.Description); d != "" {
		fmt.Fprintf(&b, "description: %s\n", yamlString(d))
	}
	b.WriteString("---\n\n")
	b.WriteString(generatedHeader)
	b.WriteString("\n\n")
	b.WriteString(strings.TrimRight(p.Body, "\n"))
	b.WriteString("\n")
	if err := os.WriteFile(dest, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", p.Path, err)
	}
	return nil
}

// yamlString quotes a frontmatter scalar safely. Descriptions are authored prose and routinely
// contain colons, quotes and backticks, every one of which breaks a bare YAML scalar.
func yamlString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", " ")
	return "\"" + strings.TrimSpace(s) + "\""
}

// firstLine reduces an authored multi-paragraph description to its opening SENTENCE for the
// frontmatter `description:` (which Starlight renders as the page subtitle and meta tag).
//
// What happens to the REMAINDER differs by page kind, and the difference matters: an entity page
// writes the full description into its body (writeCandyPage / the plugin pages), so nothing is
// lost. A skill recipe card does NOT — generateSkills emits only the skill's markdown body — so
// for those the truncated remainder is dropped from the site entirely. That is why the 11
// harness references living in skill frontmatter `description:` fields are published nowhere.
//
// Descriptions are authored as hard-wrapped block scalars, so cutting at the first newline would
// truncate mid-sentence ("… the generator that"). Instead the first paragraph is unwrapped and
// then cut at its first sentence end.
func firstLine(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	// Take the first paragraph, then unwrap it.
	if i := strings.Index(s, "\n\n"); i >= 0 {
		s = s[:i]
	}
	s = strings.Join(strings.Fields(s), " ")
	// Cut at the first sentence end, ignoring an abbreviation-style "e.g." / "i.e.".
	for i := 0; i+1 < len(s); i++ {
		if s[i] != '.' || s[i+1] != ' ' {
			continue
		}
		if i >= 3 && (strings.HasSuffix(s[:i], "e.g") || strings.HasSuffix(s[:i], "i.e")) {
			continue
		}
		return strings.TrimSpace(s[:i+1])
	}
	return s
}

// fence wraps content in a fenced code block of the given language.
func fence(lang, content string) string {
	content = strings.TrimRight(content, "\n")
	if content == "" {
		return ""
	}
	return "```" + lang + "\n" + content + "\n```"
}
