package docs

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/opencharly/sdk/candywalk"
	"github.com/opencharly/spec/spec"
	"gopkg.in/yaml.v3"
)

// collectCandySkills projects the candy `skill:` entities from the walked corpus into the
// skill set — the ref-driven complement to collectSkills' marketplace-corpus read. After the
// candy de-submodule cutover (Phase 3), a moved candy's skill: entity lives in its STANDALONE
// repo (fetched via CollectEntitiesRemote); the marketplace repo the docs generator also reads
// is regenerated by `charly marketplace generate`, so until that regeneration lands, the candy
// skills must be projected HERE from the same remote-aware walk. Without this, a recipe page
// referencing /charly-<family>:<skill> for a moved candy's skill dangles (R1: the stale-
// marketplace divergence the Phase-3 RDD surfaced).
//
// The projection mirrors plugin-marketplace's emit_skills.go: each candy `skill:` entity
// (e.Name, family from spec.Skill.Family, content from spec.Skill.Content) becomes one skill
// card under its family's plugin dir.
func collectCandySkills(ents []candywalk.Entity) []skill {
	var out []skill
	for _, e := range ents {
		if e.Kind != "skill" {
			continue
		}
		var s spec.Skill
		if err := e.Value.Decode(&s); err != nil {
			continue
		}
		// Agent-type skills are emitted by the marketplace generator to agents/ (the harness
		// agent roster), NOT as recipe cards — the docs generator only projects skill cards.
		if s.Type == "agent" {
			continue
		}
		name := s.Name
		if name == "" {
			name = e.Name
		}
		refs := make([]skillReference, 0, len(s.References))
		for _, r := range s.References {
			refs = append(refs, skillReference{Stem: r.Name, Body: r.Content})
		}
		out = append(out, skill{
			PluginDir:   s.Family,
			PluginName:  "charly-" + s.Family,
			Name:        name,
			Title:       name,
			Description: s.Description,
			Body:        s.Content,
			References:  refs,
		})
	}
	return out
}

// marketplace is plugins/.claude-plugin/marketplace.json — the authoritative plugin taxonomy.
// Driving the site's recipe section from it means a NEW plugin appears on the site with no
// site-side edit at all: its bucket, description and skill list all follow from the manifest.
type marketplace struct {
	Plugins []marketplacePlugin `json:"plugins"`
}

type marketplacePlugin struct {
	Name        string `json:"name"`   // e.g. "charly-internals"
	Source      string `json:"source"` // e.g. "./internals"
	Description string `json:"description"`
	Category    string `json:"category"` // commands | kind | development | images
}

// Dir is the plugin's directory name under plugins/ (the manifest's source path, minus "./").
func (p marketplacePlugin) Dir() string { return strings.TrimPrefix(p.Source, "./") }

// Ref is the plugin half of a `/charly-<plugin>:<skill>` reference — the manifest name minus the
// `charly-` prefix, which is exactly the directory name.
func (p marketplacePlugin) Ref() string { return strings.TrimPrefix(p.Name, "charly-") }

// skill is one recipe card: a SKILL.md plus any references/*.md split files.
type skill struct {
	PluginDir   string
	PluginName  string
	Name        string
	Title       string
	Description string
	Body        string
	References  []skillReference
}

type skillReference struct {
	Stem string // file stem, e.g. "beds-and-r10"
	Body string
}

// categoryTitle maps a manifest bucket onto the site's section heading.
var categoryTitle = map[string]string{
	"commands":    "Commands — runtime CLI verbs",
	"kind":        "Kinds — schema authoring",
	"development": "Development — contributor internals",
	"images":      "Images — the deployable catalog",
}

// readMarketplace loads the plugin taxonomy from the marketplace checkout.
func readMarketplace(pluginsDir string) (*marketplace, error) {
	path := filepath.Join(pluginsDir, ".claude-plugin", "marketplace.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read marketplace.json: %w", err)
	}
	var m marketplace
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, fmt.Errorf("parse marketplace.json: %w", err)
	}
	sort.Slice(m.Plugins, func(i, j int) bool { return m.Plugins[i].Name < m.Plugins[j].Name })
	return &m, nil
}

// collectSkills reads every skill of every plugin named by the manifest. The corpus is read
// off the FILESYSTEM at the marketplace checkout (a submodule of the docs repo since the
// marketplace de-submodule cutover — the docs deploy passes its marketplace checkout via
// --plugins) — so the generated site matches whatever that checkout is at, which is not
// necessarily the gitlink the docs repo pins. On a clean checkout the two agree and git rev
// is invisible; in a worktree whose marketplace checkout has moved they do not, and
// regeneration then projects the checkout. Check the marketplace out at the commit you intend
// to publish before regenerating, or the drift gate goes red for a reason that is not obvious
// from the diff.
func collectSkills(pluginsDir string, m *marketplace) ([]skill, error) {
	var out []skill
	for _, p := range m.Plugins {
		skillsDir := filepath.Join(pluginsDir, p.Dir(), "skills")
		ents, err := os.ReadDir(skillsDir)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("read %s: %w", skillsDir, err)
		}
		for _, de := range ents {
			if !de.IsDir() {
				continue
			}
			s, err := readSkill(skillsDir, p, de.Name())
			if err != nil {
				return nil, err
			}
			if s != nil {
				out = append(out, *s)
			}
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].PluginDir != out[j].PluginDir {
			return out[i].PluginDir < out[j].PluginDir
		}
		return out[i].Name < out[j].Name
	})
	return out, nil
}

// generatedSkillHeaderRe strips the marketplace generator's DO-NOT-EDIT comment (the prune
// marker at the top of every generated SKILL.md body) before the body is published as a recipe
// page — it is an internal marker, not skill content.
var generatedSkillHeaderRe = regexp.MustCompile(`(?m)^<!-- GENERATED by .*? -->\n\n`)

func readSkill(skillsDir string, p marketplacePlugin, name string) (*skill, error) {
	path := filepath.Join(skillsDir, name, "SKILL.md")
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	front, body := splitFrontmatter(string(raw))
	// The marketplace generator marks generated SKILL.md files with a DO-NOT-EDIT HTML comment
	// at the top of the body (its prune marker). It is NOT skill content — strip it so the
	// published recipe page does not carry the internal marker.
	body = generatedSkillHeaderRe.ReplaceAllString(body, "")
	var fm struct {
		Name        string `yaml:"name"`
		Description string `yaml:"description"`
	}
	if front != "" {
		if err := yaml.Unmarshal([]byte(front), &fm); err != nil {
			return nil, fmt.Errorf("parse frontmatter of %s: %w", path, err)
		}
	}
	title := fm.Name
	if title == "" {
		title = name
	}
	s := skill{
		PluginDir:   p.Dir(),
		PluginName:  p.Name,
		Name:        name,
		Title:       title,
		Description: fm.Description,
		Body:        body,
	}
	refDir := filepath.Join(skillsDir, name, "references")
	refEnts, err := os.ReadDir(refDir)
	if err == nil {
		for _, re := range refEnts {
			if re.IsDir() || !strings.HasSuffix(re.Name(), ".md") {
				continue
			}
			rraw, err := os.ReadFile(filepath.Join(refDir, re.Name()))
			if err != nil {
				return nil, fmt.Errorf("read reference %s: %w", re.Name(), err)
			}
			// Reference files carry no frontmatter by contract — only the entry SKILL.md does;
			// they DO carry the marketplace generator's DO-NOT-EDIT marker, stripped here too.
			s.References = append(s.References, skillReference{
				Stem: strings.TrimSuffix(re.Name(), ".md"),
				Body: generatedSkillHeaderRe.ReplaceAllString(string(rraw), ""),
			})
		}
		sort.Slice(s.References, func(i, j int) bool { return s.References[i].Stem < s.References[j].Stem })
	} else if !os.IsNotExist(err) {
		return nil, fmt.Errorf("read %s: %w", refDir, err)
	}
	return &s, nil
}

// splitFrontmatter separates a leading `---` YAML block from the markdown body.
func splitFrontmatter(s string) (front, body string) {
	if !strings.HasPrefix(s, "---\n") {
		return "", s
	}
	rest := s[len("---\n"):]
	end := strings.Index(rest, "\n---\n")
	if end < 0 {
		return "", s
	}
	return rest[:end], strings.TrimPrefix(rest[end+len("\n---\n"):], "\n")
}

// skillPagePath is the content-root-relative file for a skill's card.
func skillPagePath(s skill) string {
	return fmt.Sprintf("recipes/%s/%s.md", s.PluginDir, s.Name)
}

// skillSitePath is the URL Starlight serves that card at.
func skillSitePath(s skill) string {
	return fmt.Sprintf("/recipes/%s/%s/", s.PluginDir, s.Name)
}

func referencePagePath(s skill, stem string) string {
	return fmt.Sprintf("recipes/%s/%s/%s.md", s.PluginDir, s.Name, stem)
}

func referenceSitePath(s skill, stem string) string {
	return fmt.Sprintf("/recipes/%s/%s/%s/", s.PluginDir, s.Name, stem)
}

// buildResolver indexes every skill and reference page so cross-references can be rewritten and
// anything unresolvable can be reported as a build error.
func buildResolver(skills []skill, m *marketplace) linkResolver {
	dirToRef := map[string]string{}
	for _, p := range m.Plugins {
		dirToRef[p.Dir()] = p.Ref()
	}
	lr := linkResolver{
		skillPages: map[string]string{},
		refPages:   map[string]string{},
	}
	for _, s := range skills {
		ref := dirToRef[s.PluginDir]
		lr.skillPages[ref+":"+s.Name] = skillSitePath(s)
		for _, r := range s.References {
			lr.refPages[s.PluginDir+"/"+s.Name+"/"+r.Stem] = referenceSitePath(s, r.Stem)
		}
	}
	return lr
}

// generateSkills emits every recipe card and its reference pages.
// collectDangling runs the skill rewrite pass WITHOUT writing any page, collecting every
// unresolvable cross-reference. It is the gate that must run BEFORE the prune: a refused run
// (a dangling reference) must leave the output tree intact. Mirrors generateSkills' loop but
// drops the page writes — the rewrite is pure, so the dangling set is identical.
func collectDangling(skills []skill, m *marketplace, lr linkResolver) []danglingRef {
	var dangling []danglingRef
	for _, s := range skills {
		_, d := lr.rewrite(s.Body, s.PluginDir, s.Name, skillPagePath(s))
		dangling = append(dangling, d...)
		for _, r := range s.References {
			_, rd := lr.rewrite(r.Body, s.PluginDir, s.Name, referencePagePath(s, r.Stem))
			dangling = append(dangling, rd...)
		}
	}
	return dangling
}

func generateSkills(outRoot string, skills []skill, m *marketplace, lr linkResolver) (int, []danglingRef, error) {
	dirToPlugin := map[string]marketplacePlugin{}
	for _, p := range m.Plugins {
		dirToPlugin[p.Dir()] = p
	}
	var dangling []danglingRef
	count := 0
	for _, s := range skills {
		p := dirToPlugin[s.PluginDir]
		body, d := lr.rewrite(s.Body, s.PluginDir, s.Name, skillPagePath(s))
		dangling = append(dangling, d...)

		var b strings.Builder
		fmt.Fprintf(&b, "*Recipe card from the `%s` plugin (%s).*\n\n", p.Name, categoryLabel(p.Category))
		if len(s.References) > 0 {
			b.WriteString("This card has additional detail pages:\n\n")
			for _, r := range s.References {
				fmt.Fprintf(&b, "- [%s](%s)\n", r.Stem, referenceSitePath(s, r.Stem))
			}
			b.WriteString("\n")
		}
		b.WriteString(body)

		if err := (page{
			Path:        skillPagePath(s),
			Title:       s.Title,
			Description: s.Description,
			Body:        b.String(),
		}).write(outRoot); err != nil {
			return 0, nil, err
		}
		count++

		for _, r := range s.References {
			rbody, rd := lr.rewrite(r.Body, s.PluginDir, s.Name, referencePagePath(s, r.Stem))
			dangling = append(dangling, rd...)
			intro := fmt.Sprintf("*Detail page of the [%s](%s) recipe card.*\n\n", s.Title, skillSitePath(s))
			if err := (page{
				Path:        referencePagePath(s, r.Stem),
				Title:       fmt.Sprintf("%s — %s", s.Title, r.Stem),
				Description: fmt.Sprintf("Detail page of the %s recipe card.", s.Title),
				Body:        intro + rbody,
			}).write(outRoot); err != nil {
				return 0, nil, err
			}
			count++
		}
	}
	return count, dangling, nil
}

func categoryLabel(c string) string {
	if t, ok := categoryTitle[c]; ok {
		return t
	}
	return c
}
