package docs

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writeTree materializes a synthetic content tree for the site-link gate.
func writeTree(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for rel, body := range files {
		p := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", p, err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatalf("write %s: %v", p, err)
		}
	}
	return root
}

// TestVerifySiteLinksCatchesDeadLink is the regression guard for the defect that shipped on a
// GREEN build: the home page, the quickstart and the generated vision page all linked to
// `/recipes/`, no page was emitted there (the sidebar entry is an autogenerated group label, which
// produces no route), and the harness cross-reference gate did not cover the class at all.
func TestVerifySiteLinksCatchesDeadLink(t *testing.T) {
	root := writeTree(t, map[string]string{
		"index.mdx":           "See the [recipe cards](/recipes/) and the [quickstart](/start/quickstart/).\n",
		"start/quickstart.md": "Back [home](/).\n",
	})

	err := verifySiteLinks(root)
	if err == nil {
		t.Fatal("expected a dead-link error for /recipes/, got nil")
	}
	if !strings.Contains(err.Error(), "/recipes/") {
		t.Errorf("error should name the dead target, got: %v", err)
	}
	if !strings.Contains(err.Error(), "index.mdx") {
		t.Errorf("error should name the source page, got: %v", err)
	}
	// The links that DO resolve must not be reported.
	if strings.Contains(err.Error(), "/start/quickstart/") {
		t.Errorf("a resolving link was reported as dead: %v", err)
	}
}

func TestVerifySiteLinksPassesWhenComplete(t *testing.T) {
	root := writeTree(t, map[string]string{
		"index.mdx":           "See the [recipe cards](/recipes/) and the [quickstart](/start/quickstart/).\n",
		"recipes/index.md":    "The cards.\n",
		"start/quickstart.md": "Back [home](/).\n",
	})
	if err := verifySiteLinks(root); err != nil {
		t.Errorf("expected a complete tree to pass, got: %v", err)
	}
}

// TestVerifySiteLinksIgnoresNonPageTargets keeps the gate from firing on things that are not
// routes: assets served from public/, on-page anchors, and external links.
func TestVerifySiteLinksIgnoresNonPageTargets(t *testing.T) {
	root := writeTree(t, map[string]string{
		"index.mdx": strings.Join([]string{
			"An [asset](/favicon.svg).",
			"An [anchor](/start/quickstart/#build).",
			"An [external](https://example.com/nope/).",
			"A [page](/start/quickstart/).",
		}, "\n"),
		"start/quickstart.md": "x\n",
	})
	if err := verifySiteLinks(root); err != nil {
		t.Errorf("expected non-page targets to be ignored, got: %v", err)
	}
}

// TestVerifySiteLinksResolvesIndexRoutes locks in the route derivation: `foo/index.md` serves at
// `/foo/`, and the root index serves at `/`.
func TestVerifySiteLinksResolvesIndexRoutes(t *testing.T) {
	root := writeTree(t, map[string]string{
		"index.mdx":        "[section](/section/)\n",
		"section/index.md": "[home](/)\n",
	})
	if err := verifySiteLinks(root); err != nil {
		t.Errorf("index routes should resolve, got: %v", err)
	}
}

// TestVerifySiteLinksCoversFrontmatterLinks closes the gap round 3 flagged: a Starlight splash
// page declares its call-to-action targets as `link:` fields in YAML frontmatter, which never
// appear in the markdown body. Those are the most prominent links on the site, so a markdown-only
// scan left exactly the wrong ones unchecked.
func TestVerifySiteLinksCoversFrontmatterLinks(t *testing.T) {
	root := writeTree(t, map[string]string{
		"index.mdx": strings.Join([]string{
			"---",
			"title: Home",
			"hero:",
			"  actions:",
			"    - text: Get started",
			"      link: /start/install/",
			"    - text: Missing",
			"      link: /nope/",
			"---",
			"",
			"Body.",
		}, "\n"),
		"start/install.md": "x\n",
	})

	err := verifySiteLinks(root)
	if err == nil {
		t.Fatal("expected a dead frontmatter link to be reported, got nil")
	}
	if !strings.Contains(err.Error(), "/nope/") {
		t.Errorf("error should name the dead frontmatter target, got: %v", err)
	}
	if strings.Contains(err.Error(), "/start/install/") {
		t.Errorf("a resolving frontmatter link was reported as dead: %v", err)
	}
}
