package docs

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// internalLinkPattern matches a markdown link to a site-absolute path — `](/foo/bar/)`.
var internalLinkPattern = regexp.MustCompile(`\]\((/[^)\s"']*)\)`)

// siteAbsoluteDeepLinkPattern matches a markdown link to a deep URL on the site itself —
// `](https://opencharly.ai/foo/…` — but never the bare homepage link, whose trailing slash is
// absent and which callers that need it rewrite separately (rewriting it first would corrupt
// every deeper URL).
var siteAbsoluteDeepLinkPattern = regexp.MustCompile(`\]\(https://opencharly\.ai/([^)]*)`)

// rewriteSiteAbsoluteDeepLinks turns a source's absolute deep links to the site into
// site-relative ones. On the published page an absolute self-link would leave and re-enter over
// the network on every internal navigation, and verifySiteLinks could not check it; in the
// SOURCE the absolute form is exactly right, because a GitHub reader has no site root to resolve
// a relative path against.
func rewriteSiteAbsoluteDeepLinks(body string) string {
	return siteAbsoluteDeepLinkPattern.ReplaceAllString(body, "](/$1")
}

// frontmatterLinkPattern matches a site-absolute target in a YAML frontmatter field — the
// `link:` of a Starlight splash-page hero action, for instance. Those are real navigation
// targets that never appear in the markdown body, so a markdown-only scan leaves the most
// prominent links on the site (the home page's call-to-action buttons) unchecked.
var frontmatterLinkPattern = regexp.MustCompile(`(?m)^\s*(?:-\s+)?link:\s*["']?(/[^\s"']*)`)

// verifySiteLinks resolves EVERY site-absolute markdown link in the content tree against the
// pages that tree actually emits, and fails if any of them points at nothing.
//
// This is deliberately broader than the harness cross-reference gate in links.go, which only ever
// covered `/charly-<plugin>:<skill>` references inside skill bodies. That narrower gate let a real
// dead link ship: the generated vision page rewrites the repo's `plugins/README.md` onto
// `/recipes/`, the hand-authored home page and quickstart linked there too, and no page was
// emitted at that path — the sidebar entry for it is an autogenerated GROUP LABEL, which produces
// no route. Three dead links, and a green build, because nothing checked the class.
//
// It also covers the HAND-AUTHORED pages, which the generator does not own but does sit alongside.
// Checking them here is what makes "an unresolvable internal link fails the build" true as a
// statement about the site rather than only about the skill corpus — and a docs build that only
// half-checks its links is worse than one that admits it does not check them, because the claim
// gets believed.
func verifySiteLinks(outRoot string) error {
	routes, pages, err := collectRoutes(outRoot)
	if err != nil {
		return err
	}

	type deadLink struct{ source, target string }
	var dead []deadLink

	for _, p := range pages {
		raw, err := os.ReadFile(p.file)
		if err != nil {
			return fmt.Errorf("read %s: %w", p.file, err)
		}
		matches := internalLinkPattern.FindAllStringSubmatch(string(raw), -1)
		if front, _ := splitFrontmatter(string(raw)); front != "" {
			matches = append(matches, frontmatterLinkPattern.FindAllStringSubmatch(front, -1)...)
		}
		for _, m := range matches {
			target := m[1]
			// Strip fragment and query — a link to an on-page anchor resolves to its page.
			if i := strings.IndexAny(target, "#?"); i >= 0 {
				target = target[:i]
			}
			if target == "" {
				continue
			}
			// Non-page assets (favicon, images, downloads) live in public/ and are not routes.
			if filepath.Ext(target) != "" {
				continue
			}
			if !routes[normalizeRoute(target)] {
				rel, _ := filepath.Rel(outRoot, p.file)
				dead = append(dead, deadLink{source: filepath.ToSlash(rel), target: m[1]})
			}
		}
	}
	if len(dead) == 0 {
		return nil
	}

	byTarget := map[string][]string{}
	for _, d := range dead {
		byTarget[d.target] = append(byTarget[d.target], d.source)
	}
	targets := make([]string, 0, len(byTarget))
	for t := range byTarget {
		targets = append(targets, t)
	}
	sort.Strings(targets)

	var b strings.Builder
	fmt.Fprintf(&b, "%d internal link target(s) resolve to no page:\n", len(targets))
	for _, t := range targets {
		srcs := dedupe(byTarget[t])
		sort.Strings(srcs)
		fmt.Fprintf(&b, "  %s\n    linked from: %s\n", t, strings.Join(srcs, ", "))
	}
	b.WriteString("every internal link must resolve to a page the site emits")
	return fmt.Errorf("%s", b.String())
}

type contentPage struct {
	file  string // absolute path
	route string
}

// collectRoutes maps the content tree onto the routes Starlight serves it at.
func collectRoutes(outRoot string) (map[string]bool, []contentPage, error) {
	routes := map[string]bool{}
	var pages []contentPage

	err := filepath.WalkDir(outRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		ext := filepath.Ext(path)
		if ext != ".md" && ext != ".mdx" {
			return nil
		}
		rel, err := filepath.Rel(outRoot, path)
		if err != nil {
			return err
		}
		route := "/" + filepath.ToSlash(strings.TrimSuffix(rel, ext))
		// `foo/index.md` serves at `/foo/`; the root index page serves at `/`.
		route = strings.TrimSuffix(route, "/index")
		if route == "/index" || route == "" {
			route = "/"
		}
		routes[normalizeRoute(route)] = true
		pages = append(pages, contentPage{file: path, route: route})
		return nil
	})
	if err != nil {
		return nil, nil, fmt.Errorf("walk content tree: %w", err)
	}
	sort.Slice(pages, func(i, j int) bool { return pages[i].file < pages[j].file })
	return routes, pages, nil
}

// normalizeRoute makes route comparison insensitive to the trailing slash Starlight adds.
func normalizeRoute(r string) string {
	if r == "/" {
		return "/"
	}
	return "/" + strings.Trim(r, "/")
}
